# Generated by Django 5.0.7 on 2024-10-04 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_diary", "0002_alter_diarydate_options_alter_diarynotes_options"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diarynotes",
            name="diary_date",
        ),
        migrations.CreateModel(
            name="DiaryDay",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("day", models.DateField()),
                (
                    "diary_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_profile",
                        to="profiles.profile",
                        verbose_name="Diary Date",
                    ),
                ),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
        migrations.AddField(
            model_name="diarynotes",
            name="diary_day",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_date",
                to="daily_diary.diaryday",
                verbose_name="Diary Note",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("gym_sets", models.IntegerField()),
                (
                    "gym_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_date",
                        to="daily_diary.diaryday",
                        verbose_name="Gym",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="DiaryDate",
        ),
    ]
