# Generated by Django 5.0.7 on 2024-10-04 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_diary", "0003_remove_diarynotes_diary_date_diaryday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarynotes",
            name="diary_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_day",
                to="daily_diary.diaryday",
                verbose_name="Diary Note",
            ),
        ),
    ]
