# Generated by Django 5.0.7 on 2024-10-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_diary", "0004_alter_diarynotes_diary_day"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diarynotes",
            options={"ordering": ["time"]},
        ),
        migrations.RemoveField(
            model_name="diarynotes",
            name="note_type",
        ),
        migrations.AlterField(
            model_name="gym",
            name="gym_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gym_day",
                to="daily_diary.diaryday",
                verbose_name="Gym",
            ),
        ),
    ]
