# Generated by Django 5.0.7 on 2024-10-05 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_diary",
            "0005_alter_diarynotes_options_remove_diarynotes_note_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="gym_difdiculty",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="gym_reps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="gym_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="gym_weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="track_by_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gym",
            name="gym_sets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GymMachine",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("machine_name", models.CharField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daily_diary.gym",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
