# Generated by Django 5.0.7 on 2024-10-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_diary", "0006_gym_gym_difdiculty_gym_gym_reps_gym_gym_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="track_by_time",
        ),
        migrations.RemoveField(
            model_name="gymmachine",
            name="test",
        ),
        migrations.AddField(
            model_name="gymmachine",
            name="gym",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="daily_diary.gym",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gymmachine",
            name="track_by_time",
            field=models.BooleanField(default=False),
        ),
    ]
