# Generated by Django 5.0.7 on 2024-10-05 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_diary",
            "0007_remove_gym_track_by_time_remove_gymmachine_test_and_more",
        ),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="gym_day",
        ),
        migrations.RemoveField(
            model_name="diarynotes",
            name="diary_day",
        ),
        migrations.RemoveField(
            model_name="gymmachine",
            name="gym",
        ),
        migrations.AlterModelOptions(
            name="diarynotes",
            options={"ordering": ["-note_type", "time"]},
        ),
        migrations.AddField(
            model_name="diarynotes",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("diary", "Diary"),
                    ("nutrition", "Nutrition"),
                    ("gym", "Gym"),
                    ("feelings", "Feelings"),
                ],
                default="diary",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="DiaryDate",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_profile",
                        to="profiles.profile",
                        verbose_name="Diary Date",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="diarynotes",
            name="diary_date",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_date",
                to="daily_diary.diarydate",
                verbose_name="Diary Note",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DiaryDay",
        ),
        migrations.DeleteModel(
            name="Gym",
        ),
        migrations.DeleteModel(
            name="GymMachine",
        ),
    ]
