# Generated by Django 5.0.7 on 2024-10-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutritions", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NutritionDay",
            new_name="DailyNutritionTracker",
        ),
        migrations.RenameModel(
            old_name="Nutrition",
            new_name="Nutritions",
        ),
    ]
