# Generated by Django 5.0.7 on 2024-10-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutritions", "0002_rename_nutritionday_dailynutritiontracker_and_more"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Nutritions",
            new_name="Nutrition",
        ),
        migrations.RenameModel(
            old_name="DailyNutritionTracker",
            new_name="NutritionDay",
        ),
    ]
