# Generated by Django 5.0.7 on 2024-10-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutritions", "0003_rename_nutritions_nutrition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooddata",
            old_name="callories",
            new_name="calories",
        ),
    ]
